

#--------------------------项目信息--------------------------



#--------------------------debug--------------------------
debug: false


#--------------------------Server--------------------------
server:
  port: 8081
  servlet:
    context-path: /zuozuo


#--------------------------context-path--------------------------
host: localhost
ctx: http://${host}:${server.port}${server.servlet.context-path}

#--------------------------Spring--------------------------
spring:

#--------------------------banner--------------------------
  main:
    banner-mode: console

#--------------------------datasource--------------------------
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/core?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root





#--------------------------redis--------------------------
  redis:
    host: localhost
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    password:
    ssl: false


#--------------------------application--------------------------
  application:
    name: zuozuo
  freemarker:
    suffix: .html
    template-loader-path: classpath:/templates/


#--------------------------mvc--------------------------
  mvc:
     static-path-pattern: /static/**



#--------------------------jpa--------------------------
  jpa:
    show-sql: true

#--------------------------邮件服务--------------------------
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    port: 25
    test-connection: true
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
    protocol: smtp
    username: m15197447018@163.com
    password: woaini151

#--------------------------mvc--------------------------
mybatis:
  mapper-locations: classpath:mapper/*.xml


#--------------------------druid--------------------------
druid:
  jdbcUrl: ${spring.datasource.url}
  username: ${spring.datasource.username}
  password: ${spring.datasource.password}
  driverClassName: ${spring.datasource.driver-class-name}
  validationQuery: 'SELECT 1'
  initialSize: 5
  maxActive: 20
  minIdle: 5
  maxWait: 60000
  maxOpenPreparedStatements: -1
  poolPreparedStatements: true
  testOnBorrow: true
  testOnReturn: false
  testWhileIdle: true




#--------------------------监控和管理--------------------------

management:
  endpoint:
    beans:
      enabled: true
    auditevents:
      enabled: true




#--------------------------日志--------------------------

logging:
  path: D:\\logs\\








